version: "3"

services:

  postgres:
    image: postgis/postgis:10-2.5-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

  datamodel:
    build: ./data_model
    environment:
      POSTGRES_URI: postgres://postgres:postgres@postgres/postgres
      # User variables
      SRID: ${SRID}
    restart: on-failure

volumes:
  pgdata:
