name: Test and build Docker image

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  workflow_dispatch:


jobs:
  docker-tests:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "build dockerfile"
        run: docker build -f .docker/Dockerfile --tag opengisch/siro:unstable .

      - name: "initialize container"
        run: |
          docker run -d -p 5432:5432 --name siro opengisch/siro:unstable
          docker exec siro init_db.sh wait
          docker exec siro init_db.sh build -d

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install

      - name: "test images"
        run: docker exec siro sh -c "PGSERVICE=siro_build /src/test/official_sign_images.sh"
        
      - name: "schema lint"
        run: |
          npm i -g schemalint
          cp .schemalintrc.js.template .schemalintrc.js
          schemalint

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "push to dockerhub"
        if: github.event_name != 'pull_request'
        run: |
          docker push opengisch/siro:unstable

      - name: "push release to dockerhub"
        if: github.event_name != 'pull_request' && github.ref != 'refs/heads/master'
        run: |
          docker tag opengisch/siro:unstable opengisch/siro:${GITHUB_REF##*/}
          docker push opengisch/siro:${GITHUB_REF##*/}
          docker tag opengisch/siro:unstable opengisch/siro:latest
          docker push opengisch/siro:latest

      - name: "failure logs"
        if: failure()
        run: |
          docker logs siro
